"""users add fileds about_me and last_seen

Revision ID: 51e9f84a8233
Revises: 18111d0c2158
Create Date: 2018-04-30 05:35:17.276148

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '51e9f84a8233'
down_revision = '18111d0c2158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
