"""followers

Revision ID: 9382099bae13
Revises: 51e9f84a8233
Create Date: 2018-05-03 21:38:54.787994

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9382099bae13'
down_revision = '51e9f84a8233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
                    sa.Column('follower_id', sa.Integer(), nullable=True),
                    sa.Column('followed_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
